# Generated by Django 5.0.6 on 2024-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_full_name', models.CharField(max_length=255)),
                ('father_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_full_name', models.CharField(max_length=255)),
                ('mother_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('id_or_birth_cert_number', models.CharField(max_length=100, verbose_name='N.ID or Birth Cert. No')),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('province_or_state', models.CharField(max_length=100, verbose_name='Province or State (of origin)')),
                ('zip_or_lga', models.CharField(max_length=100, verbose_name='ZIP or LGA (of origin)')),
                ('town_of_origin', models.CharField(max_length=100, verbose_name='Town (of origin)')),
                ('permanent_address', models.TextField()),
                ('residential_address', models.TextField()),
            ],
        ),
    ]
