# Generated by Django 5.0.6 on 2024-12-24 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuadianOrParent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father')], max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('id_or_birth_cert_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N.ID or Birth Cert. No')),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('contact_phone', models.CharField(max_length=15)),
                ('province_or_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province or State (of origin)')),
                ('zip_or_lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='ZIP or LGA (of origin)')),
                ('town_of_origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Town (of origin)')),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('residential_address', models.TextField(blank=True, null=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.guadianorparent')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
