# Generated by Django 5.0.6 on 2025-01-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guadianorparent',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
