# Generated by Django 5.0.6 on 2025-01-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='academic_year',
            field=models.DateField(auto_now_add=True),
        ),
    ]
