# Generated by Django 5.0.6 on 2025-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_guadianorparent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guadianorparent',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
