# Generated by Django 5.0.6 on 2024-12-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ManyToManyField(blank=True, null=True, related_name='parents', to='api.guadianorparent'),
        ),
    ]
