# Generated by Django 5.0.6 on 2025-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentclass_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='academic_year',
            field=models.CharField(max_length=100),
        ),
    ]
