# Generated by Django 5.0.6 on 2024-12-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_or_birth_cert_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N.ID or Birth Cert. No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='province_or_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Province or State (of origin)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='town_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town (of origin)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_or_lga',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ZIP or LGA (of origin)'),
        ),
    ]
