# Generated by Django 5.0.6 on 2025-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_guadianorparent_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=models.ManyToManyField(related_name='parents', to='api.guadianorparent'),
        ),
    ]
