# Generated by Django 5.0.6 on 2025-01-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studentclass_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='academic_year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
