# Generated by Django 5.0.6 on 2024-12-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='town_of_origin',
            new_name='place_of_origin',
        ),
    ]
