# Generated by Django 5.0.6 on 2024-12-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_town_of_origin_student_place_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guadianorparent',
            name='first_name',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guadianorparent',
            name='last_name',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
