# Generated by Django 5.0.6 on 2024-12-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_guadianorparent_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guadianorparent',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guadianorparent',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
