# Generated by Django 5.0.6 on 2025-01-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_results_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='student_classes', to='api.subject'),
        ),
    ]
