# Generated by Django 5.0.6 on 2024-12-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_guadianorparent_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guadianorparent',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
