# Generated by Django 5.0.6 on 2024-12-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_guadianorparent_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
