# Generated by Django 5.0.6 on 2025-01-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guadianorparent',
            name='relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian')], max_length=100),
        ),
    ]
