# Generated by Django 5.0.6 on 2025-01-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_studentclass_admission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='tags',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
