# Generated by Django 5.0.6 on 2025-01-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_studentclass_class_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='api.tag'),
        ),
    ]
