# Generated by Django 5.0.6 on 2025-01-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_student_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='academic_year',
            field=models.CharField(blank=True, default='2025', max_length=100, null=True),
        ),
    ]
