# Generated by Django 5.0.6 on 2025-01-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_skill_skillcategory_skillassessment_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessment',
            name='academic_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='exam_session',
            field=models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=20),
        ),
    ]
