# Generated by Django 5.0.6 on 2025-01-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_skillassessment_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillassessment',
            name='academic_year',
            field=models.CharField(blank=True, default=2025, max_length=100),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='exam_session',
            field=models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default='First Term', max_length=20),
        ),
    ]
