# Generated by Django 5.0.6 on 2025-02-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_skillassessment_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='debtor',
            field=models.BooleanField(default=False),
        ),
    ]
