# Generated by Django 5.0.6 on 2025-02-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_student_debtor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_academic_session', models.CharField(max_length=20)),
                ('active_academic_year', models.CharField(max_length=4)),
                ('active_academic_term', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=255)),
                ('school_motto', models.CharField(blank=True, max_length=255, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('core_values', models.TextField(blank=True, null=True)),
                ('school_email', models.EmailField(max_length=254)),
                ('school_phone', models.CharField(max_length=20)),
                ('support_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('school_address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('city_state', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('school_head_title', models.CharField(blank=True, max_length=50, null=True)),
                ('active_services', models.CharField(choices=[('portal_website', 'School Portal and Website'), ('portal_only', 'School Portal Only')], max_length=50)),
                ('absence_sms_parent', models.BooleanField(default=False)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('watermark_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
            ],
        ),
    ]
