# Generated by Django 5.0.6 on 2025-02-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='active_services',
            field=models.CharField(blank=True, choices=[('portal_website', 'School Portal and Website'), ('portal_only', 'School Portal Only')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/images/'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='city_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/images/'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/images/'),
        ),
    ]
