# Generated by Django 5.0.6 on 2025-02-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_systemsettings_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
