# Generated by Django 5.0.6 on 2025-02-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_systemsettings_school_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('email_username', models.CharField(blank=True, max_length=255, null=True)),
                ('email_password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(blank=True, default=True, null=True)),
                ('use_ssl', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pale_education_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('other_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=20, null=True)),
                ('enable_sms', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('can_access_system_settings', models.BooleanField(default=False)),
                ('can_manage_sessions', models.BooleanField(default=False)),
                ('can_send_emails', models.BooleanField(default=False)),
                ('can_send_sms', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='active_academic_session',
            new_name='fees_support_contact',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='year_one',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='absence_sms_parent',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='active_academic_term',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='active_academic_year',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='additional_image_results',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='school_head_title',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='school_logo',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='site_icon',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='support_contact',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='user',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='absence_sms_to_parent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='head_staff_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='active_services',
            field=models.CharField(choices=[('portal_website', 'School Portal and Website'), ('portal_only', 'School Portal Only')], default='portal_website', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_motto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='school_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.academicsession')),
            ],
        ),
    ]
