# Generated by Django 5.0.6 on 2025-02-06 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_academicsession_user_academicterm_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsession',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='academicterm',
            name='session',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='year_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AcademiccSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='academicterm',
            name='_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.academiccsession'),
        ),
    ]
