# Generated by Django 5.0.6 on 2025-02-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_academicsession_end_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicterm',
            old_name='_session',
            new_name='session',
        ),
    ]
