# Generated by Django 5.0.6 on 2025-02-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename__session_academicterm_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccsession',
            name='session',
        ),
        migrations.AddField(
            model_name='academiccsession',
            name='_session',
            field=models.CharField(default='Nothing', max_length=20, unique=True),
        ),
    ]
