# Generated by Django 5.0.6 on 2025-02-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_academiccsession_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.academiccsession'),
        ),
    ]
