# Generated by Django 5.0.6 on 2025-02-08 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_academicterm_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('term_name', 'session', 'is_active'), name='unique_active_term_per_session'),
        ),
    ]
