# Generated by Django 5.0.6 on 2025-02-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_academicterm_unique_active_term_per_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccsession',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
