# Generated by Django 5.0.6 on 2025-02-08 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_academiccsession_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='school_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='academiccsession',
            constraint=models.UniqueConstraint(fields=('start_year', 'end_year', '_session', 'is_active'), name='unique_active_session'),
        ),
    ]
