# Generated by Django 5.0.6 on 2024-12-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_parent_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
