# Generated by Django 5.0.6 on 2024-12-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_user_ptr_remove_teacher_user_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Parent', 'Parent'), ('TestUser', 'TestUser')], default='TestUser', max_length=100),
        ),
    ]
