import React from "react";
import {
  Box,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  TableContainer,
  Paper,
  LinearProgress,
  Card,
  Button,
} from "@mui/material";
import { useNavigate } from "react-router-dom";
import PublishIcon from '@mui/icons-material/Publish';

// Mock Data for Table
const studentsData = [
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
  {
    name: "JOLAYEMI JAMES TAIWO",
    scores: {
      socialStudies: { score: 64, grade: "B" },
      english: { score: 85, grade: "A" },
      mathematics: { score: 60, grade: "B" },
      basicScience: { score: 75, grade: "A" },
      basicTechnology: { score: 23, grade: "F" },
      agriculturalScience: { score: 63, grade: "B" },
      physicalEducation: { score: 96, grade: "A" },
      civicEducation: { score: 81, grade: "A" },
      computerEducation: { score: 79, grade: "A" },
      indigenousLanguage: { score: 57, grade: "C" },
      religiousStudies: { score: 74, grade: "A" },
      homeEconomics: { score: 70, grade: "A" },
    },
    total: 827,
    averageGradePoint: 4.167,
    averageTotalScore: "68.917%",
  },
  {
    name: "DEMO STUDENT",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 83, grade: "A" },
      mathematics: { score: 80, grade: "A" },
      basicScience: { score: 90, grade: "A" },
      basicTechnology: { score: 57, grade: "C" },
      agriculturalScience: { score: 68, grade: "B" },
      physicalEducation: { score: 63, grade: "B" },
      civicEducation: { score: 52, grade: "C" },
      computerEducation: { score: 62, grade: "B" },
      indigenousLanguage: { score: 62, grade: "B" },
      religiousStudies: { score: 69, grade: "A" },
      homeEconomics: { score: 72, grade: "A" },
    },
    total: 821,
    averageGradePoint: 4.083,
    averageTotalScore: "68.417%",
  },
  {
    name: "JAMES ENYINNAYA",
    scores: {
      socialStudies: { score: 81, grade: "A" },
      english: { score: 75, grade: "A" },
      mathematics: { score: 48, grade: "D" },
      basicScience: { score: 76, grade: "A" },
      basicTechnology: { score: 78, grade: "A" },
      agriculturalScience: { score: 39, grade: "F" },
      physicalEducation: { score: 92, grade: "A" },
      civicEducation: { score: 68, grade: "B" },
      computerEducation: { score: 72, grade: "A" },
      indigenousLanguage: { score: 59, grade: "C" },
      religiousStudies: { score: 76, grade: "A" },
      homeEconomics: { score: 50, grade: "C" },
    },
    total: 814,
    averageGradePoint: 3.917,
    averageTotalScore: "67.833%",
  },
];

// Component
const ReviewAndPublishResults: React.FC = () => {
  const navigate = useNavigate()
  return (
    <Box sx={{ width: '100%', maxWidth: { sm: '100%', md: '1700px' } }}>
      <Typography
          variant="h6"
          sx={{ marginBottom: "20px", fontWeight: "bold", color: "#3f51b5" }}
        >
          Review & Publish Results
        </Typography>
        <Card sx={{width:'100%', overflowX:"auto"}}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Students</TableCell>
                    {Object.keys(studentsData[0].scores).map((subject) => (
                      <TableCell key={subject}>
                        {subject
                          .replace(/([A-Z])/g, " $1") // Split camelCase
                          .replace(/^./, (str) => str.toUpperCase())}{" "}
                        (Total Score)
                      </TableCell>
                    ))}
                    <TableCell>Grand Total</TableCell>
                    <TableCell>Average Grade Point</TableCell>
                    <TableCell>Average Total Score %</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {studentsData.map((student) => (
                    <TableRow key={student.name}>
                      <TableCell>{student.name}</TableCell>
                      {Object.values(student.scores).map(({ score, grade }, idx) => (
                        <TableCell key={idx}>
                          {score} ({grade})
                        </TableCell>
                      ))}
                      <TableCell>{student.total}/1200</TableCell>
                      <TableCell>{student.averageGradePoint.toFixed(3)}</TableCell>
                      <TableCell>
                        <Box sx={{ display: "flex", alignItems: "center" }}>
                          {student.averageTotalScore}
                          <LinearProgress
                            variant="determinate"
                            value={parseFloat(student.averageTotalScore)}
                            sx={{
                              width: "100px",
                              marginLeft: "8px",
                            }}
                          />
                        </Box>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
        </Card>
        <Box sx={{display:'flex', justifyContent:'center', alignItems:'center', width:'100%', mt:'2.3rem'}}>
          <Button variant='contained' onClick={()=>navigate("/publishResults")}> Looks Good, Next!</Button>
        </Box>
    </Box>
  );
};

export default ReviewAndPublishResults;
